// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID             int64
	Name           string
	PriceInCenters int32
	Quantity       int32
	CreatedAt      pgtype.Timestamptz
}
