// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         int64
	CustomerID int64
	CreatedAt  pgtype.Timestamptz
}

type OrderItem struct {
	ID         int64
	OrderID    int64
	ProductID  int64
	Quantity   int32
	PriceCents int32
}

type Product struct {
	ID             int64
	Name           string
	PriceInCenters int32
	Quantity       int32
	CreatedAt      pgtype.Timestamptz
}
